services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recsys-app
    ports:
      - "8000:8000"
    depends_on:
      - prometheus
    environment:
      - MODEL_VERSION=v1.0
      - REGION=us

  prometheus:
    image: prom/prometheus:latest
    container_name: recsys-prom
    volumes:
      - ./prometheus:/etc/prometheus:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: recsys-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_RENDERING_SERVER_URL=http://renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
      - GF_LOG_FILTERS=rendering:debug
    depends_on:
      - prometheus
      - renderer

  renderer:
    image: grafana/grafana-image-renderer:latest
    container_name: recsys-grafana-renderer
